resources:
  memory: 512
  execution_timeout: 60s
  
runtime:
  python: 3.11

environment:
  - AMOCRM_DOMAIN
  - ACCESS_TOKEN
  - AMOCRM_CLIENT_ID
  - AMOCRM_CLIENT_SECRET
  - AMOCRM_REFRESH_TOKEN
  - AMOCRM_REDIRECT_URI
